### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by Denubis** [dvanic/metametalesson#1]
Oof. Doing everything in public, in github issues is already tough.
https://github.com/carpentrycon/carpentryconhome-proposals/issues/39#issuecomment-649565213 says we're approved. 

Let's work out timelines and tasks here to start with? By end of week?

**Comment by dvanic** [comment]
Yes, I think that's a good idea. I propose a "diary" document, to allows us to also freehand-document what we are doing. I think the first step is to confirm our scheduled slot - are you happy to liase with central re:this?

**Comment by Denubis** [comment]
Yes, next week though. Just added a reminder for myself on carpentries slack to do so monday.
